from pydantic import BaseModel, Field
from datetime import datetime, timezone
from enum import Enum

class PlatformType(str, Enum):
    WHATSAPP = "whatsapp"
    TELEGRAM = "telegram"

class IncomingMessage(BaseModel):
    platform: PlatformType
    sender_id: str = Field(..., description="The phone number or user ID of the sender of the message note it should be uniqu on it's platform")
    destination_agent_id: str = Field(..., description="The ID of the AI agent handling this message")
    text: str = Field(..., description="The actual message content from the user")
    timestamp: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))

class OutgoingMessage(BaseModel):
    platform: PlatformType
    sender_id: str = Field(..., description="The phone number or user ID to reply to")
    destination_agent_id: str = Field(..., description="The ID of the AI agent sending the reply")
    response_text: str = Field(..., description="The final text generated by the LLM")
    timestamp: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    